# Generated by Django 4.1.2 on 2022-10-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('documento', models.IntegerField()),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
